# See 02-workflow-events/README.md for more information
# about different triggers for GitHub Actions.

name: 03 workflow events - workflow_dispatch

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Mansi Gupta'
        required: true
        default: 'GitHub Actions'

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "I've been triggered by a(n) ${{ github.event_name }} event."